Repository Alohomora-team/AlohomoraAPI, pull requests merged in 2019-11, with the labels that each got.

#28 12 melhorar informacoes readme
  README.md
  iot.png
  logo_alohomora.png
Labels: documentation

#31 30 paralelizar ci
  .travis.yml
Labels: DevOps

#44 36 padronizar persistencia audio
  CHANGELOG.md
  app/accounts/migrations/0002_auto_20191112_1451.py
  app/accounts/models.py
  app/accounts/mutations/residents.py
  app/accounts/queries/residents.py
  app/accounts/tests/test_models.py
  app/accounts/tests/test_schema.py
  app/accounts/tests/test_voice_belongs.py
  app/accounts/types.py
  app/accounts/utility.py
  teste.py
Labels: enhancement

#47 46-Corrigir-changelog
  CHANGELOG.md
Labels: documentation, enhancement

#50 24 corrigir duplicacoes codigo
  README.md
  app/accounts/mutations/users.py
  app/accounts/queries/residents.py
  teste.py
Labels: enhancement

#65 56 testar dtw
  app/accounts/mutations/residents.py
  app/accounts/queries/residents.py
  app/accounts/tests/audios/aline_base.wav
  app/accounts/tests/audios/aline_clean.wav
  app/accounts/tests/audios/aline_noised.wav
  app/accounts/tests/audios/felipe_base.wav
  app/accounts/tests/audios/felipe_clean.wav
  app/accounts/tests/audios/felipe_noised.wav
  app/accounts/tests/audios/impostor.wav
  app/accounts/tests/audios/marcos_base.wav
  app/accounts/tests/audios/marcos_clean.wav
  app/accounts/tests/audios/marcos_noised.wav
  app/accounts/tests/audios/mateus_base.wav
  app/accounts/tests/audios/mateus_clean.wav
  app/accounts/tests/audios/mateus_noised.wav
  app/accounts/tests/audios/paulo_base.wav
  app/accounts/tests/audios/paulo_clean.wav
  app/accounts/tests/audios/paulo_noised.wav
  app/accounts/tests/audios/pedro_base.wav
  app/accounts/tests/audios/pedro_clean.wav
  app/accounts/tests/audios/pedro_noised.wav
  app/accounts/tests/audios/samuel_base.wav
  app/accounts/tests/audios/samuel_clean.wav
  app/accounts/tests/audios/samuel_noised.wav
  app/accounts/tests/audios/sergio_base.wav
  app/accounts/tests/audios/sergio_clean.wav
  app/accounts/tests/audios/sergio_noised.wav
  app/accounts/tests/audios/silva_base.wav
  app/accounts/tests/audios/silva_clean.wav
  app/accounts/tests/audios/silva_noised.wav
  app/accounts/tests/audios/victor_base.wav
  app/accounts/tests/audios/victor_clean.wav
  app/accounts/tests/audios/victor_noised.wav
  app/accounts/tests/audios/vitor_base.wav
  app/accounts/tests/audios/vitor_clean.wav
  app/accounts/tests/audios/vitor_noised.wav
  app/accounts/tests/data.py
  app/accounts/tests/graphql/test_resident.py
  app/accounts/tests/test_voice_belongs.py
  app/accounts/utility.py
  docker/Dockerfile
Labels: enhancement

#71 #70 atualizar dockerfile de Deploy
  deploy.Dockerfile
Labels: DevOps, bug

#72 48 adicionar robustez cadastro voz
  app/accounts/queries/audio.py
  app/accounts/utility.py
  app/alohomora/schema.py
Labels: enhancement
